[supervisord]
nodaemon=true

[program:mosquitto]
command=/bin/sh -c "/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf | sed 's/^/mosquitto | /'"
environment=LD_LIBRARY_PATH="/opt/musl-libs"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mobius]
command=/bin/sh -c "node mobius | sed 's/^/mobius | /'"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0